// this file has been auto-generated by ctestlib version: 0.01a

#include "CTestLib.h"

extern void register_AddTest(void);
extern void register_StarchTest(void);
int main(int argc, char* argv) {
	register_AddTest();
	register_StarchTest();
	return 0;
}
        

        